version: "3.8"
services:
  mongo1:
    image: mongo:latest
    command: mongod --replSet rs0 --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
  mongo2:
    image: mongo:latest
    command: mongod --replSet rs0 --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongo2-data:/data/db
  mongo3:
    image: mongo:latest
    command: mongod --replSet rs0 --port 27019
    ports:
      - "27019:27019"
    volumes:
      - mongo3-data:/data/db
volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
